# Site settings
title: Another Bit
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.anotherbit.com" # the base hostname & protocol for your site
